# Generated by Django 5.2.1 on 2025-07-28 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_entry_photos_entry_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Entrée', 'verbose_name_plural': 'Entrées'},
        ),
    ]
